name: Reusable workflow

on:
  workflow_call:
    inputs:
      additional:
        type: string
        description: "TEST"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: demo workflow job
        run: echo This is a demo start workflow

